import { ai, cleanJsonString, withRetry } from '../generation/modelGateway';
import { StoryBlueprint, WorkflowLog } from '../../types';

export async function runIllustratorPass(
    prompts: { spreadNumber: number, imagePrompt: string, storyText: string }[],
    blueprint: StoryBlueprint | undefined,
    childName: string,
    secondCharacterName?: string
): Promise<{ result: { spreadNumber: number, imagePrompt: string, storyText: string }[], log: WorkflowLog }> {

    const startTime = Date.now();

    try {
        return await withRetry(async () => {
            const promptInstruction = `
            ROLE: Senior Art Director / Master Illustrator Agent.
            TASK: Review and polish a sequence of image generation prompts for a children's book. Your goal is to strictly prevent AI model hallucinations, ensure visual continuity, and lock down the composition.
            
            **THE BLUEPRINT (Intended Story Structure):**
            ${JSON.stringify(blueprint || {})}

            **THE GENERATED PROMPTS (Needs Auditing):**
            ${JSON.stringify(prompts)}
            
            **ART DIRECTOR'S MANIFESTO (CRITICAL SANITY CHECKS):**
            
            1. **NO TYPOGRAPHY HALLUCINATIONS:**
               - Image generation models love to accidentally draw text, letters, or words on the images.
               - You MUST ensure every single prompt explicitly forbids text generation.
               - Check the 'COMPOSITION' and negative prompt lines. They must aggressively say "No text, no letters, no typography, no words, no signatures".
               
            2. **CHARACTER COUNT & CONTINUITY:**
               - The main character is [IMAGE 1]. If there is a second character, they are [IMAGE 2].
               - You must make sure no extra random characters or humans are added to the 'Action' or 'Setting' lines. 
               - If the prompt mentions "a crowd", change it to "an empty landscape" or focus ONLY on [IMAGE 1] to prevent the AI from generating random mangled faces in the background.
               
            3. **PERSPECTIVE & FRAMING ALIGNMENT:**
               - Ensure the composition rules (e.g. "LEFT two-thirds of the frame") match the blueprint's intent and are clearly stated.
               - You MUST explicitly retain the exact "Framing: Wide establishing shot" and "No dutch angles" instruction in the COMPOSITION block so the book feels like a cohesive cinematic sequence. Do not erase this.
               
            4. **CONSTRAINTS (DO NOT BREAK THE TEMPLATE):**
               - DO NOT change or remove the \`**CHARACTER REFERENCES:**\` or \`**STYLE:**\` blocks. These are critical DNA injections. 
               - Only edit the \`**SCENE:**\` and \`**COMPOSITION:**\` blocks if they violate the typography rules above.
               - ABSOLUTE MANDATE: You are forbidden from changing the core Setting Location or core Action originally generated by the prompt engineer. You are an editor, not a writer. Your ONLY job is to remove typography/text hallucinations from the prompt. Preserve the original storyline and physical surroundings EXACTLY as intended.
               - You MUST return exactly ${prompts.length} prompt objects.
               
            OUTPUT JSON SCHEMA:
            [
                { 
                  "spreadNumber": 1, 
                  "storyText": "Original untouched story text...",
                  "imagePrompt": "The fully audited and polished prompt string..." 
                },
                ... (Must be exactly ${prompts.length} items)
            ]
            `;

            const model = ai().getGenerativeModel({
                model: 'gemini-2.0-flash',
                generationConfig: { responseMimeType: "application/json" }
            });

            const response = await model.generateContent(promptInstruction);
            const editedPrompts = JSON.parse(cleanJsonString(response.response.text()));

            if (!Array.isArray(editedPrompts) || editedPrompts.length !== prompts.length) {
                console.warn(`Illustrator Agent returned ${editedPrompts.length} pages instead of ${prompts.length}. Length mismatch.`);
                if (editedPrompts.length < prompts.length) throw new Error("Illustrator dropped spreads.");
            }

            return {
                result: editedPrompts,
                log: {
                    stage: 'QA',
                    timestamp: startTime,
                    inputs: { promptCount: prompts.length },
                    outputs: { auditedCount: editedPrompts.length },
                    status: 'Success',
                    durationMs: Date.now() - startTime
                }
            };
        });
    } catch (e: any) {
        console.error("Illustrator Agent Failed, falling back to original prompts:", e);
        return {
            result: prompts,
            log: {
                stage: 'QA',
                timestamp: startTime,
                inputs: {},
                outputs: { error: e.message, fallback: true },
                status: 'Failed',
                durationMs: Date.now() - startTime
            }
        };
    }
}
