import { NextRequest, NextResponse } from 'next/server';
import { sanitizePrompt } from '../../../../services/generation/imageGenerator';
import { ai as getAi } from '../../../../services/generation/modelGateway';

/**
 * POST /api/generate/outpaint
 *
 * Accepts a padded/scaled spread illustration with empty (white) borders.
 * Passes it to Gemini with a strict "generative fill / outpaint" mandate:
 *   — Keep all original characters, poses, and central scene intact.
 *   — Generate and fill the empty/white space seamlessly to match the existing environment.
 *
 * Body:
 *   imageBase64     — padded image as base64 (no data: prefix needed)
 *   stylePrompt     — art style string for style consistency
 */

async function toRawBase64(input: string): Promise<string | null> {
    if (!input) return null;
    try {
        if (input.startsWith('http')) {
            const res = await fetch(input);
            if (!res.ok) throw new Error(`Failed to fetch image: ${res.statusText}`);
            const arrayBuffer = await res.arrayBuffer();
            return Buffer.from(arrayBuffer).toString('base64');
        }
        return input.includes(',') ? input.split(',')[1] : input;
    } catch (err) {
        console.error("Error converting image to base64:", err);
        return null;
    }
}

export async function POST(req: NextRequest) {
    try {
        const body = await req.json();
        const {
            imageBase64,
            stylePrompt,
            childDNA,
            secondDNA
        } = body;

        if (!imageBase64) {
            return NextResponse.json(
                { error: 'imageBase64 is required' },
                { status: 400 }
            );
        }

        const safeStyle = sanitizePrompt(stylePrompt || 'Painterly children\'s book illustration style');

        // Build multi-modal contents array
        const contents: any[] = [];

        // Normalize all inputs to RAW BASE64
        const rawSpread = await toRawBase64(imageBase64);
        if (!rawSpread) return NextResponse.json({ error: 'Failed to process spread image' }, { status: 400 });
        contents.push({ inlineData: { mimeType: 'image/jpeg', data: rawSpread } });

        const rawChild = await toRawBase64(childDNA);
        if (rawChild) {
            contents.push({ inlineData: { mimeType: 'image/jpeg', data: rawChild } });
        }

        const rawSecond = await toRawBase64(secondDNA);
        if (rawSecond) {
            contents.push({ inlineData: { mimeType: 'image/jpeg', data: rawSecond } });
        }

        const editPrompt = `You are a professional children's book illustrator performing a GENERATIVE FILL (OUTPAINT) on an existing scene.

**THE ORIGINAL PADDED ILLUSTRATION:** See Attached Image 1 (inlineData[0]). This image contains a central artwork surrounded by blank/empty space (white borders) because it was zoomed out or panned.
${childDNA ? `\n**CHARACTER REFERENCE A:** See Attached Image ${secondDNA ? '2' : '2'} — match this character's face, hair, and clothing exactly if they appear in the new generated areas.` : ''}${secondDNA ? `\n**CHARACTER REFERENCE B:** See final attached image — match this character identically.` : ''}

**EDIT INSTRUCTION:**
Seamlessly fill in the blank/white borders by extending the existing landscape, background, and environment. Ensure the transition between the original central art and the new extended borders is completely invisible and seamless. 

**STRICT RULES:**
- PRESERVE: Do NOT alter the central original artwork. Keep all existing characters, objects, and layout exactly as they are in the non-white areas.
- EXTEND: Only imagine and generate the missing parts of the environment to fill the entire 16:9 panoramic canvas.
- PRESERVE STYLE: Match the existing art style perfectly — "${safeStyle}".
- NO TEXT: Zero letters, words, or typography anywhere in the output image.
- QUALITY: Ultra-high resolution, 4K quality, masterpiece children's illustration.`;

        contents.push({ text: editPrompt });

        const model = getAi().getGenerativeModel({
            model: 'gemini-2.5-flash-image',
        });

        const result = await model.generateContent({
            contents: [{ role: 'user', parts: contents }],
            generationConfig: {
                temperature: 0.1, // Low temp for more consistency with original
                topK: 32,
                topP: 0.9,
            }
        });

        const generatedImages = result.response.candidates?.[0]?.content?.parts
            ?.filter(p => p.inlineData)
            ?.map(p => p.inlineData?.data);

        if (!generatedImages || generatedImages.length === 0) {
            throw new Error("No image generated by the outpainting model.");
        }

        return NextResponse.json({
            success: true,
            imageBase64: generatedImages[0]
        });

    } catch (error: any) {
        console.error('Outpaint Error:', error);
        return NextResponse.json(
            { error: error.message || 'Failed to outpaint image' },
            { status: 500 }
        );
    }
}
