-- Lock down tables created in subscription_schema.sql by enabling Row Level Security
ALTER TABLE heroes ENABLE ROW LEVEL SECURITY;
ALTER TABLE hero_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE hero_theme_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE artifacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE webhook_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_locks ENABLE ROW LEVEL SECURITY;
